const response = [
{id: 2, name: 'Arizona Diamondbacks', logo: 'https://media-2.api-sports.io/baseball/teams/2.png', national: false},
{id: 3, name: 'Atlanta Braves', logo: 'https://media-2.api-sports.io/baseball/teams/3.png', national: false},
{id: 4, name: 'Baltimore Orioles', logo: 'https://media-2.api-sports.io/baseball/teams/4.png', national: false},
{id: 5, name: 'Boston Red Sox', logo: 'https://media-1.api-sports.io/baseball/teams/5.png', national: false},
{id: 39, name: 'Canada', logo: 'https://media-1.api-sports.io/baseball/teams/39.png', national: false},
{id: 6, name: 'Chicago Cubs', logo: 'https://media-2.api-sports.io/baseball/teams/6.png', national: false},
{id: 7, name: 'Chicago White Sox', logo: 'https://media-2.api-sports.io/baseball/teams/7.png', national: false},
{id: 8, name: 'Cincinnati Reds', logo: 'https://media-1.api-sports.io/baseball/teams/8.png', national: false},
{id: 9, name: 'Cleveland Indians', logo: 'https://media-1.api-sports.io/baseball/teams/9.png', national: false},
{id: 10, name: 'Colorado Rockies', logo: 'https://media-1.api-sports.io/baseball/teams/10.png', national: false},
{id: 12, name: 'Detroit Tigers', logo: 'https://media-2.api-sports.io/baseball/teams/12.png', national: false},
{id: 15, name: 'Houston Astros', logo: 'https://media-1.api-sports.io/baseball/teams/15.png', national: false},
{id: 16, name: 'Kansas City Royals', logo: 'https://media-2.api-sports.io/baseball/teams/16.png', national: false},
{id: 17, name: 'Los Angeles Angels', logo: 'https://media-2.api-sports.io/baseball/teams/17.png', national: false},
{id: 18, name: 'Los Angeles Dodgers', logo: 'https://media-2.api-sports.io/baseball/teams/18.png', national: false},
{id: 19, name: 'Miami Marlins', logo: 'https://media-1.api-sports.io/baseball/teams/19.png', national: false},
{id: 20, name: 'Milwaukee Brewers', logo: 'https://media-1.api-sports.io/baseball/teams/20.png', national: false},
{id: 21, name: 'Minnesota G.', logo: 'https://media-1.api-sports.io/baseball/teams/21.png', national: false},
{id: 22, name: 'Minnesota Twins', logo: 'https://media-1.api-sports.io/baseball/teams/22.png', national: false},
{id: 24, name: 'New York Mets', logo: 'https://media-1.api-sports.io/baseball/teams/24.png', national: false},
{id: 25, name: 'New York Yankees', logo: 'https://media-1.api-sports.io/baseball/teams/25.png', national: false},
{id: 43, name: 'Northeastern', logo: 'https://media-1.api-sports.io/baseball/teams/43.png', national: false},
{id: 26, name: 'Oakland Athletics', logo: 'https://media-1.api-sports.io/baseball/teams/26.png', national: false},
{id: 27, name: 'Philadelphia Phillies', logo: 'https://media-1.api-sports.io/baseball/teams/27.png', national: false},
{id: 28, name: 'Pittsburgh Pirates', logo: 'https://media-2.api-sports.io/baseball/teams/28.png', national: false},
{id: 30, name: 'San Diego Padres', logo: 'https://media-1.api-sports.io/baseball/teams/30.png', national: false},
{id: 31, name: 'San Francisco Giants', logo: 'https://media-1.api-sports.io/baseball/teams/31.png', national: false},
{id: 32, name: 'Seattle Mariners', logo: 'https://media-2.api-sports.io/baseball/teams/32.png', national: false},
{id: 46, name: 'Southeastern', logo: 'https://media-1.api-sports.io/baseball/teams/46.png', national: false},
{id: 33, name: 'St.Louis Cardinals', logo: 'https://media-2.api-sports.io/baseball/teams/33.png', national: false},
{id: 34, name: 'Tampa Bay Rays', logo: 'https://media-1.api-sports.io/baseball/teams/34.png', national: false},
{id: 35, name: 'Texas Rangers', logo: 'https://media-2.api-sports.io/baseball/teams/35.png', national: false},
{id: 36, name: 'Toronto Blue Jays', logo: 'https://media-2.api-sports.io/baseball/teams/36.png', national: false},
{id: 37, name: 'Washington Nationals', logo: 'https://media-1.api-sports.io/baseball/teams/37.png', national: false}
]
export default response;